### ISSUE TITLE
TSP Validation Datasets

### ISSUE THREAD

**Issue by janmikula** [Edward-Sun/DIFUSCO#4]
Dear authors, Thank you for your excellent research. I am trying to reproduce your TSP experiments, but it is unclear how to obtain the validation datasets. I followed the `README.md` in the `data` folder, downloaded the test datasets, and generated the train datasets with your code. Therefore, now I have `tsp{50,100,500,1000,10000}_{train,test}_concorde.txt`, but I am missing the validation splits. I couldn't figure out the exact process based on your `reproducing_scripts.md`. Could you please help me with this?

**Comment by Edward-Sun** [comment]
The validation set is only used to supervise training (by early-stopping), so you can just create your own validation set by another random seed other than training and test.

However, since we usually do not observe over-fitting in our CO model, I think you can just use the last checkpoint for evaluation.
